import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generatePDFReport(result, recommendations) {
  if (!result) return;

  const doc = new jsPDF();

  const reportId = `SAI-${Date.now()}`;
  const generatedAt = new Date().toLocaleString();

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text("SENTINEL AI", 105, 13, { align: "center" });

  doc.setFontSize(11);
  doc.text(
    "Enterprise Network Intrusion Detection System",
    105,
    21,
    { align: "center" }
  );

  // Report Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);

  doc.text(`Report ID : ${reportId}`, 14, 42);
  doc.text(`Generated : ${generatedAt}`, 14, 49);
  doc.text("Status : Completed", 14, 56);

  // Summary Table
  autoTable(doc, {
    startY: 65,
    head: [["Field", "Value"]],
    body: [
      ["Dataset", result.datasetName],
      ["Model", result.model],
      ["Prediction", result.prediction],
      ["Confidence", `${result.confidence}%`],
      ["Severity", result.severity],
      ["Packets Analyzed", result.packetsAnalyzed],
      ["Safe Traffic", `${result.safeTraffic}%`],
      ["Malicious Traffic", `${result.maliciousTraffic}%`],
      ["Analysis Time", result.analysisTime],
    ],
  });

  // Attack Summary
  const finalY = doc.lastAutoTable.finalY + 12;

  doc.setFontSize(16);
  doc.text("Attack Summary", 14, finalY);

  autoTable(doc, {
    startY: finalY + 5,
    head: [["Attack Type", "Packets"]],
    body: Object.entries(result.attackSummary || {}).map(
      ([attack, count]) => [attack, count]
    ),
  });

  // Recommendations
  const recommendationY = doc.lastAutoTable.finalY + 12;

  doc.setFontSize(16);
  doc.text("Security Recommendations", 14, recommendationY);

  let currentY = recommendationY + 8;

  recommendations.forEach((item) => {
    doc.setFontSize(11);
    doc.text(`• ${item}`, 18, currentY);
    currentY += 7;
  });

  // Footer
  doc.setDrawColor(180);
  doc.line(14, 285, 196, 285);

  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by Sentinel AI Enterprise IDS Platform",
    105,
    291,
    { align: "center" }
  );

  doc.save(
  `Sentinel_AI_${result.datasetName.replace(".csv", "")}_${Date.now()}.pdf`
);
}